# Profil PROD
server.port=9090
servicename=BarberBooking-PROD
spring.datasource.url=jdbc:postgresql://prod-db-server:5432/baza_serwisu_prod
spring.datasource.username=prod_user
spring.datasource.password=ProdPass123
_service.name=12.34.21.29
_service.port=7832
_service.api_path=/api/call/hello
