# Profil DEV
server.port=8081
servicename=BarberBooking-DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/baza_serwisu
spring.datasource.username=postgres
spring.datasource.password=BackEnd123
_service.name=127.0.0.1
_service.port=7832
_service.api_path=/api/call/hello
