# application.properties
spring.application.name=barberbooking

# default profile
spring.profiles.default=dev
spring.profiles.active=dev


# Serwer domyślny (dla dev)
server.port=8080

# Nazwa serwisu (może być nadpisana w profilach)
servicename=BarberBooking
