# Nazwa aplikacji
spring.application.name=barberbooking

# ------------------------------------------
# Połączenie z PostgreSQL
# ------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/baza_serwisu
spring.datasource.username=postgres        # lub piratGolibroda jeśli stworzyłeś użytkownika
spring.datasource.password=TwojeHaslo      # hasło do bazy PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ------------------------------------------
# Hibernate / JPA
# ------------------------------------------
spring.jpa.show-sql=true                  # pokazuje zapytania SQL w konsoli
spring.jpa.hibernate.ddl-auto=update      # automatyczne tworzenie/aktualizacja tabel wg encji
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ------------------------------------------
# Serwer
# ------------------------------------------
server.port=8080                          # port na którym działa aplikacja
