# ------------------------------------------
# Nazwa aplikacji
# ------------------------------------------
spring.application.name=barberbooking

# ------------------------------------------
# Połączenie z PostgreSQL
# ------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/baza_serwisu
spring.datasource.username=postgres
# hasło do bazy PostgreSQL
spring.datasource.password=student
spring.datasource.driver-class-name=org.postgresql.Driver

# ------------------------------------------
# Hibernate / JPA
# ------------------------------------------
# pokazuje zapytania SQL w konsoli
spring.jpa.show-sql=true
# automatyczne tworzenie/aktualizacja tabel wg encji
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ------------------------------------------
# Serwer
# ------------------------------------------
# port na którym działa aplikacja
server.port=8080
